name: pose_camera_app
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.1.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  camera: ^0.11.0
  image: ^4.2.0
  ultralytics_yolo: ^0.1.25
  image_picker: ^0.8.7
  gal: ^2.3.2

  flutter_litert: ^2.0.7
  flutter_litert_flex: ^0.0.5

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/models/yolov8n-pose_float16.tflite
    - assets/models/nima_aesthetic_fp16_flex.tflite