// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC22_j5V2LEBbKbZhm-tz3Vwl9d5WveXyc',
    appId: '1:871010001836:web:af6813e12da803ff7f9009',
    messagingSenderId: '871010001836',
    projectId: 'pozyapp-646b5',
    authDomain: 'pozyapp-646b5.firebaseapp.com',
    storageBucket: 'pozyapp-646b5.firebasestorage.app',
    measurementId: 'G-NHT993EBPD',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDMxQdlshNLFoaV_TzpHzry3d4W2Y60LMg',
    appId: '1:871010001836:android:388fcbf9c5237b927f9009',
    messagingSenderId: '871010001836',
    projectId: 'pozyapp-646b5',
    storageBucket: 'pozyapp-646b5.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCFbprai4lPPE0kbnRSbFy6bGrs7xaEGPA',
    appId: '1:871010001836:ios:6f5f115111e41f6f7f9009',
    messagingSenderId: '871010001836',
    projectId: 'pozyapp-646b5',
    storageBucket: 'pozyapp-646b5.firebasestorage.app',
    iosBundleId: 'com.example.poseCameraApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCFbprai4lPPE0kbnRSbFy6bGrs7xaEGPA',
    appId: '1:871010001836:ios:6f5f115111e41f6f7f9009',
    messagingSenderId: '871010001836',
    projectId: 'pozyapp-646b5',
    storageBucket: 'pozyapp-646b5.firebasestorage.app',
    iosBundleId: 'com.example.poseCameraApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC22_j5V2LEBbKbZhm-tz3Vwl9d5WveXyc',
    appId: '1:871010001836:web:f3bcc2b95155e93b7f9009',
    messagingSenderId: '871010001836',
    projectId: 'pozyapp-646b5',
    authDomain: 'pozyapp-646b5.firebaseapp.com',
    storageBucket: 'pozyapp-646b5.firebasestorage.app',
    measurementId: 'G-V7CRL87V2P',
  );

}